name: Deploy PROD

on:
  workflow_dispatch:

jobs:
  cd:
    name: Deploy production
    runs-on: self-hosted
    steps:
      - name: Deploy to production
        run: |
          cd ~
          ssh ap009 '
            if [ -d "dwh-airbyte" ]
            then
              cd ~/dwh-airbyte
              git pull git@github-dwh-airbyte:nrcmedia/dwh-airbyte.git main
            else
              git clone -b main --single-branch git@github-dwh-airbyte:nrcmedia/dwh-airbyte.git
              cd ~/dwh-airbyte
            fi

            docker compose down
            ./run-ab-platform.sh &
          '